using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using fire.Native;
using fire.Runtime;

namespace fire.Compiler
{
    /// <summary>The result of a native build: where the program (or, for a toolchain that only writes files, the folder) is, and what the tools said.</summary>
    public sealed record NativeBuildResult(bool Ok, string Output, string Log);

    /// <summary>
    /// Builds a program natively: translate it to C++ (<see cref="CppGenerator"/>) for a target, write the runtime and the platform package of the target next to it,
    /// and let the toolchain of the configuration (<see cref="NativeConfig"/>) turn it into a program - or only write the files (and build files) of a project.
    /// </summary>
    public static class NativeBuilder
    {
        public const string SourceName = "fire_program.cpp";

        /// <summary>The program of <paramref name="sources"/> as C++ for <paramref name="target"/>. Compile errors of the script and
        /// <see cref="NativeNotSupportedException"/> propagate.</summary>
        public static string Generate(IReadOnlyList<string> sources, TargetProfile target, VmExecutionMode? mode = null, int? floatWidth = null, string? basePath = null, IReadOnlyList<string>? defines = null)
        {
            var linked = new Linker { BasePath = basePath, Engine = "native", Defines = defines }.CompileAndLink(sources, null, null, mode, floatWidth, target);
            return CppGenerator.Generate(linked, target);
        }

        /// <summary>Writes <paramref name="cpp"/> as <paramref name="fileName"/> into <paramref name="directory"/> with everything it includes: the runtime and the platform package of
        /// the target (a package of your own is copied from the target's <c>platformPath</c>).</summary>
        public static string WriteFiles(string directory, string cpp, TargetProfile target, string fileName = SourceName, string? configDirectory = null)
        {
            Directory.CreateDirectory(directory);
            string path = Path.Combine(directory, fileName);
            File.WriteAllText(path, cpp);
            NativeRuntimeFiles.WriteTo(directory, target.Native.Platform);
            if (target.Native.PlatformPath is { Length: > 0 } custom)
            {
                string source = Path.IsPathRooted(custom) || configDirectory == null ? custom : Path.Combine(configDirectory, custom);
                if (!Directory.Exists(source)) throw new NativeConfigException($"the platform folder '{source}' of target '{target.Name}' does not exist");
                CopyDirectory(source, Path.Combine(directory, "platform", target.Native.Platform));
            }
            return path;
        }

        /// <summary>Translates and builds. <paramref name="output"/> is the program, or the folder for a toolchain that only writes files.</summary>
        public static NativeBuildResult Build(IReadOnlyList<string> sources, NativeConfig config, TargetProfile target, ToolchainDef toolchain, string output,
            VmExecutionMode? mode = null, int? floatWidth = null, bool keepSources = false, string? basePath = null, IReadOnlyList<string>? defines = null)
        {
            string cpp = Generate(sources, target, mode, floatWidth, basePath, defines);
            string? configDirectory = config.Path == null ? null : Path.GetDirectoryName(config.Path);
            var log = new StringBuilder();

            if (toolchain.EffectiveKind == "files")
            {
                string directory = Path.GetFullPath(output);
                WriteFiles(directory, cpp, target, SourceName, configDirectory);
                if (toolchain.Layout == "idf-component")
                    File.WriteAllText(Path.Combine(directory, "CMakeLists.txt"),
                        $"# Generated by fire.Native for target '{target.Name}': the program as an ESP-IDF component (call {target.Native.Entry.Name} from the application).\n" +
                        $"idf_component_register(SRCS \"{SourceName}\"\n                       INCLUDE_DIRS \".\")\n" +
                        "target_compile_options(${COMPONENT_LIB} PRIVATE -std=gnu++17)\n");
                log.AppendLine($"{directory}: {SourceName}, fire_rt.hpp and platform/{target.Native.Platform}/ for {target.Name}; the entry point is {target.Native.Entry.Name}");
                if (!string.IsNullOrWhiteSpace(toolchain.BuildCommand))
                {
                    var (ok, text) = RunCommand(toolchain.BuildCommand!, directory);
                    log.Append(text);
                    return new NativeBuildResult(ok, directory, log.ToString());
                }
                return new NativeBuildResult(true, directory, log.ToString());
            }

            string workDir = keepSources ? Path.GetFullPath(output) + ".src" : Path.Combine(Path.GetTempPath(), "fire-native-" + Guid.NewGuid().ToString("N"));
            try
            {
                string cppFile = WriteFiles(workDir, cpp, target, SourceName, configDirectory);
                string exe = Path.GetFullPath(output);
                var (exeName, arguments) = CompilerCommand(toolchain, target, cppFile, workDir, exe);
                if (toolchain.EffectiveKind != "custom" && ToolchainDetector.Find(toolchain) == null)
                    return new NativeBuildResult(false, exe, $"The compiler '{toolchain.EffectiveCompiler}' was not found. Install it, name another one in the toolchain of {NativeConfig.FileName}, or build with the toolchain 'files' and compile the sources yourself.");
                log.AppendLine($"{exeName} {arguments}");
                var (ok, text) = Run(exeName, arguments, workDir);
                log.Append(text);
                return new NativeBuildResult(ok && File.Exists(exe), exe, log.ToString());
            }
            finally
            {
                if (!keepSources) try { Directory.Delete(workDir, true); } catch (IOException) { }
            }
        }

        /// <summary>Like <see cref="Build"/>, but what goes wrong (an error in the script, something the native backend cannot translate yet, a bad configuration) is in the result's log.</summary>
        public static NativeBuildResult BuildSafe(IReadOnlyList<string> sources, NativeConfig config, TargetProfile target, ToolchainDef toolchain, string output,
            VmExecutionMode? mode = null, int? floatWidth = null, bool keepSources = false, string? basePath = null, IReadOnlyList<string>? defines = null)
        {
            try { return Build(sources, config, target, toolchain, output, mode, floatWidth, keepSources, basePath); }
            catch (NativeNotSupportedException ex) { return new NativeBuildResult(false, output, "Not supported by the native backend yet: " + ex.Message); }
            catch (NativeConfigException ex) { return new NativeBuildResult(false, output, ex.Message); }
            catch (Exception ex) when (CommandLineRunner.IsCompileError(ex)) { return new NativeBuildResult(false, output, CompileErrors.Describe(ex)); }
        }

        /// <summary>The compiler command line for the generated file.</summary>
        public static (string Executable, string Arguments) CompilerCommand(ToolchainDef toolchain, TargetProfile target, string cppFile, string includeDir, string exe)
        {
            string kind = toolchain.EffectiveKind;
            var libs = (toolchain.Libs ?? new()).Concat(target.Native.LinkLibs).ToList();
            var includes = (toolchain.IncludeDirs ?? new()).ToList();
            if (kind == "custom")
            {
                string template = toolchain.Command ?? throw new NativeConfigException("a custom toolchain needs a command");
                string command = template.Replace("{cpp}", $"\"{cppFile}\"").Replace("{dir}", $"\"{includeDir}\"").Replace("{out}", $"\"{exe}\"")
                    .Replace("{args}", string.Join(" ", (toolchain.Args ?? new()).Concat(target.Native.CompileArgs)))
                    .Replace("{libs}", string.Join(" ", libs));
                int space = command.IndexOf(' ');
                return space < 0 ? (command, "") : (command.Substring(0, space), command.Substring(space + 1));
            }
            var args = new StringBuilder();
            if (kind == "msvc")
            {
                args.Append($"/std:{toolchain.Std ?? "c++17"} {toolchain.Optimization ?? "/O2"} ");
                foreach (string a in toolchain.Args ?? new()) args.Append(a).Append(' ');
                foreach (string a in target.Native.CompileArgs) args.Append(a).Append(' ');
                args.Append($"\"{cppFile}\" /I\"{includeDir}\" ");
                foreach (string d in includes) args.Append($"/I\"{d}\" ");
                args.Append($"/Fe:\"{exe}\" /Fo:\"{Path.Combine(includeDir, "fire_program.obj")}\"");
                foreach (string l in libs) args.Append(' ').Append(l);
            }
            else
            {
                args.Append($"-std={toolchain.Std ?? "c++17"} {toolchain.Optimization ?? "-O2"} ");
                foreach (string a in toolchain.Args ?? new()) args.Append(a).Append(' ');
                foreach (string a in target.Native.CompileArgs) args.Append(a).Append(' ');
                args.Append($"\"{cppFile}\" -I\"{includeDir}\" ");
                foreach (string d in includes) args.Append($"-I\"{d}\" ");
                args.Append($"-o \"{exe}\"");
                foreach (string l in libs) args.Append(' ').Append(l);
            }
            string exeName = ToolchainDetector.Find(toolchain) ?? toolchain.EffectiveCompiler;
            return (exeName, args.ToString());
        }

        private static (bool Ok, string Text) RunCommand(string command, string workDir)
        {
            int space = command.IndexOf(' ');
            return Run(space < 0 ? command : command.Substring(0, space), space < 0 ? "" : command.Substring(space + 1), workDir);
        }

        private static (bool Ok, string Text) Run(string exe, string arguments, string workDir)
        {
            try
            {
                using var p = Process.Start(new ProcessStartInfo(exe, arguments)
                { RedirectStandardOutput = true, RedirectStandardError = true, UseShellExecute = false, WorkingDirectory = workDir })!;
                var err = p.StandardError.ReadToEndAsync();
                string output = p.StandardOutput.ReadToEnd();
                p.WaitForExit();
                return (p.ExitCode == 0, output + err.Result);
            }
            catch (Exception ex) when (ex is System.ComponentModel.Win32Exception or IOException)
            {
                return (false, $"Could not run '{exe}': {ex.Message}\n");
            }
        }

        private static void CopyDirectory(string source, string target)
        {
            Directory.CreateDirectory(target);
            foreach (string file in Directory.GetFiles(source)) File.Copy(file, Path.Combine(target, Path.GetFileName(file)), true);
            foreach (string dir in Directory.GetDirectories(source)) CopyDirectory(dir, Path.Combine(target, Path.GetFileName(dir)));
        }

        /// <summary>The name of the program that a native build produces by default (<c>out</c>, <c>out.exe</c> on Windows).</summary>
        public static string DefaultOutput(TargetProfile target) => target.Name == "windows" ? "out.exe" : target.IsEmbedded ? "out" : "out";
    }
}
