using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using fire.Native;
using fire.Runtime;

namespace fire.Compiler
{
    /// <summary>The result of a native build: where the program (or, for a toolchain that only writes files, the folder) is, and what the tools said.</summary>
    public sealed record NativeBuildResult(bool Ok, string Output, string Log);

    /// <summary>
    /// Builds a program natively: translate it to C++ (<see cref="CppGenerator"/>) for a target, write the runtime and the platform package of the target next to it,
    /// and let the toolchain of the configuration (<see cref="NativeConfig"/>) turn it into a program - or only write the files (and build files) of a project.
    /// </summary>
    public static class NativeBuilder
    {
        public const string SourceName = "fire_program.cpp";

        /// <summary>The program of <paramref name="sources"/> as C++ for <paramref name="target"/>. Compile errors of the script and
        /// <see cref="NativeNotSupportedException"/> propagate.</summary>
        public static string Generate(IReadOnlyList<string> sources, TargetProfile target, VmExecutionMode? mode = null, int? floatWidth = null, string? basePath = null, IReadOnlyList<string>? defines = null, fire.Projects.BuildPlan? plan = null)
        {
            var linked = new Linker { BasePath = basePath, Engine = "native", Defines = defines, Plan = plan, SourcePaths = plan?.SourcePaths.Cast<string?>().ToList() }.CompileAndLink(sources, null, null, mode, floatWidth, target);
            return CppGenerator.Generate(linked, target);
        }

        /// <summary>Writes <paramref name="cpp"/> as <paramref name="fileName"/> into <paramref name="directory"/> with everything it includes: the runtime and the platform package of
        /// the target (a package of your own is copied from the target's <c>platformPath</c>).</summary>
        public static string WriteFiles(string directory, string cpp, TargetProfile target, string fileName = SourceName, string? configDirectory = null)
        {
            Directory.CreateDirectory(directory);
            string path = Path.Combine(directory, fileName);
            File.WriteAllText(path, cpp);
            NativeRuntimeFiles.WriteTo(directory, target.Native.Platform);
            if (target.Native.PlatformPath is { Length: > 0 } custom)
            {
                string source = Path.IsPathRooted(custom) || configDirectory == null ? custom : Path.Combine(configDirectory, custom);
                if (!Directory.Exists(source)) throw new NativeConfigException($"the platform folder '{source}' of target '{target.Name}' does not exist");
                CopyDirectory(source, Path.Combine(directory, "platform", target.Native.Platform));
            }
            return path;
        }

        /// <summary>Translates and builds. <paramref name="output"/> is the program, or the folder for a toolchain that only writes files.</summary>
        public static NativeBuildResult Build(IReadOnlyList<string> sources, NativeConfig config, TargetProfile target, ToolchainDef toolchain, string output,
            VmExecutionMode? mode = null, int? floatWidth = null, bool keepSources = false, string? basePath = null, IReadOnlyList<string>? defines = null, fire.Projects.BuildPlan? plan = null)
        {
            string cpp = Generate(sources, target, mode, floatWidth, basePath, defines, plan);
            string? configDirectory = config.Path == null ? null : Path.GetDirectoryName(config.Path);
            var log = new StringBuilder();

            if (toolchain.EffectiveKind == "files")
            {
                string directory = Path.GetFullPath(output);
                WriteFiles(directory, cpp, target, SourceName, configDirectory);
                if (toolchain.Layout == "idf-component")
                    File.WriteAllText(Path.Combine(directory, "CMakeLists.txt"),
                        $"# Generated by fire.Native for target '{target.Name}': the program as an ESP-IDF component (call {target.Native.Entry.Name} from the application).\n" +
                        $"idf_component_register(SRCS \"{SourceName}\"\n                       INCLUDE_DIRS \".\")\n" +
                        "target_compile_options(${COMPONENT_LIB} PRIVATE -std=gnu++17)\n");
                log.AppendLine($"{directory}: {SourceName}, fire_rt.hpp and platform/{target.Native.Platform}/ for {target.Name}; the entry point is {target.Native.Entry.Name}");
                if (!string.IsNullOrWhiteSpace(toolchain.BuildCommand))
                {
                    var (ok, text) = RunCommand(toolchain.BuildCommand!, directory);
                    log.Append(text);
                    return new NativeBuildResult(ok, directory, log.ToString());
                }
                return new NativeBuildResult(true, directory, log.ToString());
            }

            string workDir = keepSources ? Path.GetFullPath(output) + ".src" : Path.Combine(Path.GetTempPath(), "fire-native-" + Guid.NewGuid().ToString("N"));
            try
            {
                string cppFile = WriteFiles(workDir, cpp, target, SourceName, configDirectory);
                string exe = Path.GetFullPath(output);
                if (toolchain.EffectiveKind != "custom" && ToolchainDetector.Find(toolchain) == null)
                {
                    // nothing to compile with: offer to provide a toolchain (the host asks the user: install, change, cancel)
                    var provided = ToolchainProvider.Require(toolchain, "A native build translates the program to C++ and compiles it with a C++ toolchain.");
                    if (provided == null)
                        return new NativeBuildResult(false, exe, $"The compiler '{toolchain.EffectiveCompiler}' was not found. Install it, name another one in the toolchain of {NativeConfig.FileName}, or build with the toolchain 'files' and compile the sources yourself.");
                    toolchain = provided;
                }
                // a window needs the development files of SDL2: look for them, offer to download them (Windows)
                if (ToolchainProvider.RequireLibraries(toolchain, cppFile) is { } missingLibrary)
                    return new NativeBuildResult(false, exe, missingLibrary);
                var (exeName, arguments) = CompilerCommand(toolchain, target, cppFile, workDir, exe);
                log.AppendLine($"{exeName} {arguments}");
                var (ok, text) = Run(exeName, arguments, workDir);
                log.Append(text);
                bool built = ok && File.Exists(exe);
                // a Windows program with a window needs SDL2.dll next to it
                if (built && SdlSetup.IsRequiredBy(cppFile) && SdlSetup.CopyRuntimeNextTo(exe, SdlSetup.Locate(toolchain))) log.AppendLine("SDL2.dll copied next to the program.");
                return new NativeBuildResult(built, exe, log.ToString());
            }
            finally
            {
                if (!keepSources) try { Directory.Delete(workDir, true); } catch (IOException) { }
            }
        }

        /// <summary>Like <see cref="Build"/>, but what goes wrong (an error in the script, something the native backend cannot translate yet, a bad configuration) is in the result's log.</summary>
        public static NativeBuildResult BuildSafe(IReadOnlyList<string> sources, NativeConfig config, TargetProfile target, ToolchainDef toolchain, string output,
            VmExecutionMode? mode = null, int? floatWidth = null, bool keepSources = false, string? basePath = null, IReadOnlyList<string>? defines = null, fire.Projects.BuildPlan? plan = null)
        {
            try { return Build(sources, config, target, toolchain, output, mode, floatWidth, keepSources, basePath, defines, plan); }
            catch (NativeNotSupportedException ex) { return new NativeBuildResult(false, output, "Not supported by the native backend yet: " + ex.Message); }
            catch (NativeConfigException ex) { return new NativeBuildResult(false, output, ex.Message); }
            catch (Exception ex) when (CommandLineRunner.IsCompileError(ex)) { return new NativeBuildResult(false, output, CompileErrors.Describe(ex)); }
        }

        /// <summary>The compiler command line for the generated file.</summary>
        public static (string Executable, string Arguments) CompilerCommand(ToolchainDef toolchain, TargetProfile target, string cppFile, string includeDir, string exe, bool sharedLibrary = false, IEnumerable<string>? extraIncludeDirs = null)
        {
            string kind = toolchain.EffectiveKind;
            var libs = (toolchain.Libs ?? new()).Concat(target.Native.LinkLibs).ToList();
            // the generated program asks for libraries it needs (`// fire-link: SDL2` for a window): -lSDL2, SDL2.lib with msvc
            if (File.Exists(cppFile))
                foreach (string line in File.ReadLines(cppFile).Take(400))
                    if (line.StartsWith("// fire-link: ", StringComparison.Ordinal))
                    {
                        string lib = line.Substring("// fire-link: ".Length).Trim();
                        string flag = kind == "msvc" ? lib + ".lib" : "-l" + lib;
                        if (!libs.Contains(flag)) libs.Add(flag);
                    }
            var includes = (toolchain.IncludeDirs ?? new()).Concat(extraIncludeDirs ?? Array.Empty<string>()).ToList();
            var libDirs = new List<string>();
            // SDL2: where its headers and import library are (Toolchain\SDL2, SDL2_DIR, the prefix of the compiler, the system), see SdlSetup
            if (kind != "custom" && libs.Any(l => l is "-lSDL2" or "SDL2.lib") && SdlSetup.Locate(toolchain) is { } sdl)
            {
                includes.AddRange(sdl.IncludeDirs.Where(d => !includes.Contains(d)));
                libDirs.AddRange(sdl.LibDirs);
            }
            if (kind == "custom")
            {
                string template = toolchain.Command ?? throw new NativeConfigException("a custom toolchain needs a command");
                string command = template.Replace("{cpp}", $"\"{cppFile}\"").Replace("{dir}", $"\"{includeDir}\"").Replace("{out}", $"\"{exe}\"")
                    .Replace("{args}", string.Join(" ", (toolchain.Args ?? new()).Concat(target.Native.CompileArgs)))
                    .Replace("{libs}", string.Join(" ", libs));
                int space = command.IndexOf(' ');
                return space < 0 ? (command, "") : (command.Substring(0, space), command.Substring(space + 1));
            }
            var args = new StringBuilder();
            if (kind == "msvc")
            {
                args.Append($"/std:{toolchain.Std ?? "c++17"} {toolchain.Optimization ?? "/O2"} ");
                if (sharedLibrary) args.Append("/LD ");
                foreach (string a in toolchain.Args ?? new()) args.Append(a).Append(' ');
                foreach (string a in target.Native.CompileArgs) args.Append(a).Append(' ');
                args.Append($"\"{cppFile}\" /I\"{includeDir}\" ");
                foreach (string d in includes) args.Append($"/I\"{d}\" ");
                args.Append($"/Fe:\"{exe}\" /Fo:\"{Path.Combine(includeDir, "fire_program.obj")}\"");
                foreach (string l in libs) args.Append(' ').Append(l);
                if (libDirs.Count > 0) args.Append(" /link").Append(string.Concat(libDirs.Select(d => $" /LIBPATH:\"{d}\"")));
            }
            else
            {
                args.Append($"-std={toolchain.Std ?? "c++17"} {toolchain.Optimization ?? "-O2"} ");
                // a library for the VM carries its C++ runtime (MinGW: no libgcc/libstdc++ DLLs next to it), so that it also runs on a machine without the toolchain
                if (sharedLibrary) args.Append(RuntimeInformation.IsOSPlatform(OSPlatform.OSX) ? "-dynamiclib -fPIC " : RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "-shared -static-libgcc -static-libstdc++ " : "-shared -fPIC ");
                foreach (string a in toolchain.Args ?? new()) args.Append(a).Append(' ');
                foreach (string a in target.Native.CompileArgs) args.Append(a).Append(' ');
                args.Append($"\"{cppFile}\" -I\"{includeDir}\" ");
                foreach (string d in includes) args.Append($"-I\"{d}\" ");
                args.Append($"-o \"{exe}\"");
                foreach (string d in libDirs) args.Append($" -L\"{d}\"");
                foreach (string l in libs) args.Append(' ').Append(l);
            }
            string exeName = ToolchainDetector.Find(toolchain) ?? toolchain.EffectiveCompiler;
            return (exeName, args.ToString());
        }

        private static (bool Ok, string Text) RunCommand(string command, string workDir)
        {
            int space = command.IndexOf(' ');
            return Run(space < 0 ? command : command.Substring(0, space), space < 0 ? "" : command.Substring(space + 1), workDir);
        }

        internal static (bool Ok, string Text) Run(string exe, string arguments, string workDir)
        {
            try
            {
                var psi = new ProcessStartInfo(exe, arguments) { RedirectStandardOutput = true, RedirectStandardError = true, UseShellExecute = false, WorkingDirectory = workDir };
                // a portable toolchain (w64devkit) finds its other programs through the PATH: its folder comes first
                if (Path.IsPathRooted(exe) && Path.GetDirectoryName(exe) is { Length: > 0 } toolDir)
                    psi.Environment["PATH"] = toolDir + Path.PathSeparator + Environment.GetEnvironmentVariable("PATH");
                using var p = Process.Start(psi)!;
                var err = p.StandardError.ReadToEndAsync();
                string output = p.StandardOutput.ReadToEnd();
                p.WaitForExit();
                return (p.ExitCode == 0, output + err.Result);
            }
            catch (Exception ex) when (ex is System.ComponentModel.Win32Exception or IOException)
            {
                return (false, $"Could not run '{exe}': {ex.Message}\n");
            }
        }

        private static void CopyDirectory(string source, string target)
        {
            Directory.CreateDirectory(target);
            foreach (string file in Directory.GetFiles(source)) File.Copy(file, Path.Combine(target, Path.GetFileName(file)), true);
            foreach (string dir in Directory.GetDirectories(source)) CopyDirectory(dir, Path.Combine(target, Path.GetFileName(dir)));
        }

        /// <summary>Tries a toolchain: compiles a small C++ program (with the standard library and threads) for the host and runs it. The log says what was run and what came out.</summary>
        public static NativeBuildResult TestToolchain(ToolchainDef toolchain)
        {
            var log = new StringBuilder();
            if (toolchain.EffectiveKind == "files") return new NativeBuildResult(true, "", "The toolchain 'files' only writes the sources; there is nothing to test.");
            string work = Path.Combine(Path.GetTempPath(), "fire-toolchain-test-" + Guid.NewGuid().ToString("N"));
            try
            {
                Directory.CreateDirectory(work);
                string cpp = Path.Combine(work, "test.cpp");
                File.WriteAllText(cpp, "#include <cstdio>\n#include <cmath>\n#include <string>\n#include <thread>\nint main() { std::string s = \"toolchain \"; std::thread t([&] { s += \"ok\"; }); t.join(); std::printf(\"%s %g\\n\", s.c_str(), std::sqrt(16.0)); return 0; }\n");
                string exe = Path.Combine(work, OperatingSystem.IsWindows() ? "test.exe" : "test");
                var (exeName, arguments) = CompilerCommand(toolchain, TargetProfile.Host, cpp, work, exe);
                if (toolchain.EffectiveKind != "custom" && ToolchainDetector.Find(toolchain) == null)
                    return new NativeBuildResult(false, exe, $"The compiler '{toolchain.EffectiveCompiler}' was not found.");
                log.AppendLine($"{exeName} {arguments}");
                var (ok, text) = Run(exeName, arguments, work);
                log.Append(text);
                if (!ok || !File.Exists(exe)) return new NativeBuildResult(false, exe, log.ToString());
                var (ran, output) = Run(exe, "", work);
                log.Append(output);
                return new NativeBuildResult(ran && output.Contains("toolchain ok 4"), exe, log.ToString());
            }
            finally
            {
                try { Directory.Delete(work, true); } catch (IOException) { }
            }
        }

        /// <summary>The name of the program that a native build produces by default (<c>out</c>, <c>out.exe</c> on Windows).</summary>
        public static string DefaultOutput(TargetProfile target) => target.Name == "windows" ? "out.exe" : target.IsEmbedded ? "out" : "out";
    }
}
