using System.Globalization;
using System.Text;
using fire.Bytecode;
using fire.Runtime;
using fire.Values;

namespace fire.Native
{
    /// <summary>
    /// Translates a linked program (bytecode) into one C++ source file that includes <c>fire_rt.hpp</c>.
    ///
    /// Every chunk (the top-level code and each function) becomes a C++ function. The operand stack disappears: its
    /// depth is known at every instruction, so slot <c>k</c> of the stack is the C++ local <c>s{k}</c>, and the C++
    /// compiler turns those into registers. Scopes disappear as far as they hold nothing but values: a variable that
    /// lives in a scope is a C++ local (<c>B{scope}_{slot}</c>, parameters <c>P{slot}</c>, globals <c>G{slot}</c>).
    /// Jumps become <c>goto</c>.
    ///
    /// What is translated is a growing subset of the ISA (see <see cref="NativeNotSupportedException"/> for the rest):
    /// the generator never produces code with different semantics, it refuses.
    /// </summary>
    public sealed class CppGenerator
    {
        private readonly LinkedProgram _program;
        private readonly IReadOnlyList<string> _natives;
        private readonly List<Unit> _units = new() { Unit.Unitless };
        private readonly List<string> _strings = new();
        private readonly Dictionary<string, int> _stringIndex = new();
        private readonly HashSet<int> _globals = new();
        private readonly Dictionary<FunctionProto, int> _functionIndex = new(ReferenceEqualityComparer.Instance);
        private readonly List<FunctionProto> _functions = new();
        private readonly Queue<FunctionProto> _pending = new();

        private readonly TargetProfile _target;

        private CppGenerator(LinkedProgram program, TargetProfile target)
        {
            _program = program;
            _target = target;
            _natives = program.NativeNames
                ?? throw new NativeNotSupportedException("the program does not carry its native function names (link it with Linker.CompileAndLink)");
        }

        /// <summary>Generates the C++ source of the program for <paramref name="target"/> (default: the machine this runs on).
        /// Link the program with the same target (<c>Linker.CompileAndLink(..., target:)</c>) so that its libraries are checked.</summary>
        public static string Generate(LinkedProgram program, TargetProfile? target = null) => new CppGenerator(program, target ?? TargetProfile.Host).Run();

        private string Run()
        {
            var bodies = new StringBuilder();
            var mainCode = GenerateChunk(_program.Program.TopLevel, "fire_main", paramCount: 0, isMain: true);

            var functionCode = new List<string>();
            var signatures = new List<string>();
            for (int i = 0; _pending.Count > 0; i++)
            {
                var proto = _pending.Dequeue();
                int index = _functionIndex[proto];
                string signature = Signature(index, proto.ParamCount);
                signatures.Add(signature + ";");
                functionCode.Add(GenerateChunk(proto.Chunk, $"f{index}", proto.ParamCount, isMain: false, signature));
            }

            var sb = new StringBuilder();
            sb.AppendLine("// Generated by fire.Native from the bytecode - do not edit.");
            sb.AppendLine($"// target: {_target.Name}");
            sb.AppendLine($"#define FIRE_TARGET \"{_target.Name}\"");
            sb.AppendLine($"#define FIRE_TARGET_{_target.Name.ToUpperInvariant()} 1");
            sb.AppendLine($"#define FIRE_HAL_{_target.HalPackage.ToUpperInvariant()} 1");
            sb.AppendLine($"#define FIRE_DEFAULT_STACK_BYTES {_target.DefaultStackBytes}");
            if (_program.FloatWidth == 32) sb.AppendLine("#define FIRE_FLOAT32 1 // #floatwidth 32: float is a 32-bit float, like in the VM");
            sb.AppendLine("#include \"fire_rt.hpp\"");
            sb.AppendLine("using namespace fire;");
            sb.AppendLine();
            sb.AppendLine("namespace fire {");
            sb.Append("const char* const g_unitNames[] = {");
            sb.Append(string.Join(", ", _units.Select(u => u.IsUnitless ? "\"\"" : CString(u.ToString()))));
            sb.AppendLine("};");
            sb.AppendLine("}");
            sb.AppendLine();
            for (int i = 0; i < _strings.Count; i++)
            {
                var bytes = Encoding.UTF8.GetBytes(_strings[i]);
                sb.AppendLine($"static const StrObj K{i} = {{{bytes.Length}, {CString(bytes)}}};");
            }
            if (_strings.Count > 0) sb.AppendLine();
            if (_globals.Count > 0)
            {
                sb.AppendLine("static Value " + string.Join(", ", _globals.OrderBy(g => g).Select(g => $"G{g}")) + ";");
                sb.AppendLine();
            }
            foreach (var signature in signatures) sb.AppendLine(signature);
            if (signatures.Count > 0) sb.AppendLine();
            foreach (var code in functionCode) sb.AppendLine(code);
            sb.AppendLine(mainCode);
            if (_target.IsEmbedded)
            {
                // The board's startup code calls app_main (ESP-IDF) once FreeRTOS is running; there is no process to exit.
                sb.AppendLine("extern \"C\" void app_main(void) {");
                sb.AppendLine("    fire_main();");
                sb.AppendLine("    std::fflush(stdout);");
                sb.AppendLine("}");
            }
            else
            {
                sb.AppendLine("int main() {");
                sb.AppendLine("    fire_main();");
                sb.AppendLine("    std::fflush(stdout);");
                sb.AppendLine("    return 0;");
                sb.AppendLine("}");
            }
            _ = bodies;
            return sb.ToString();
        }

        private static string Signature(int index, int paramCount) =>
            $"static Value f{index}(" + string.Join(", ", Enumerable.Range(0, paramCount).Select(i => $"Value P{i}")) + ")";

        // -------------------------------------------------------------------------------------------------------------
        // Flow state: stack depth and the static scope chain (identity of the scope + number of declared slots)
        // -------------------------------------------------------------------------------------------------------------
        private const int FunctionScope = -1;
        private const int GlobalScope = -2;

        private sealed class Flow
        {
            public int Depth;
            public List<(int Id, int Declared)> Scopes = new();

            public Flow Clone() => new() { Depth = Depth, Scopes = new List<(int, int)>(Scopes) };

            public bool SameAs(Flow o) => Depth == o.Depth && Scopes.SequenceEqual(o.Scopes);
        }

        private string GenerateChunk(Chunk chunk, string name, int paramCount, bool isMain, string? signature = null)
        {
            var code = OpInfo.Decode(chunk.Code);
            var indexOfAddr = new Dictionary<int, int>();
            for (int i = 0; i < code.Count; i++) indexOfAddr[code[i].Addr] = i;

            var entry = new Flow?[code.Count];
            var start = new Flow();
            start.Scopes.Add(isMain ? (GlobalScope, 0) : (FunctionScope, paramCount));
            entry[0] = start;

            var targets = new HashSet<int>();
            var work = new Stack<int>();
            work.Push(0);
            int maxDepth = 0;
            var locals = new SortedSet<string>(StringComparer.Ordinal);

            // Pass 1: propagate states; pass 2: emit with the states found.
            Flow? Propagate(int addr, Flow state, int from)
            {
                if (!indexOfAddr.TryGetValue(addr, out int target))
                    throw new NativeNotSupportedException($"jump to {addr} inside an instruction ({name})");
                if (entry[target] == null) { entry[target] = state.Clone(); work.Push(target); }
                else if (!entry[target]!.SameAs(state))
                    throw new NativeNotSupportedException($"inconsistent stack/scope state at {addr} ({name}), reached from {from}");
                return null;
            }

            while (work.Count > 0)
            {
                int idx = work.Pop();
                var state = entry[idx]!.Clone();
                var ins = code[idx];
                var step = Step(chunk, ins, state, null, name, isMain, locals);
                maxDepth = Math.Max(maxDepth, Math.Max(entry[idx]!.Depth, state.Depth));
                if (step.JumpTarget is int jt) { targets.Add(jt); Propagate(jt, state, ins.Addr); }
                if (step.FallsThrough)
                {
                    if (idx + 1 >= code.Count) throw new NativeNotSupportedException($"code of {name} runs past its end");
                    Propagate(code[idx + 1].Addr, state, ins.Addr);
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine(signature ?? (isMain ? "static void fire_main()" : $"static Value {name}()"));
            sb.AppendLine("{");
            if (maxDepth > 0) sb.AppendLine("    Value " + string.Join(", ", Enumerable.Range(0, maxDepth).Select(i => $"s{i}")) + ";");
            var localsToDeclare = locals.Where(l => !(l.StartsWith("P") && int.Parse(l.AsSpan(1)) < paramCount)).ToList();
            if (localsToDeclare.Count > 0) sb.AppendLine("    Value " + string.Join(", ", localsToDeclare) + ";");

            for (int i = 0; i < code.Count; i++)
            {
                if (entry[i] == null) continue; // unreachable
                var ins = code[i];
                if (targets.Contains(ins.Addr)) sb.AppendLine($"L{ins.Addr}:;");
                sb.AppendLine($"    // {ins.Addr}: {ins.Op}{(ins.A.Length > 0 ? " " + string.Join(",", ins.A) : "")}");
                var state = entry[i]!.Clone();
                Step(chunk, ins, state, sb, name, isMain, locals);
            }
            if (!isMain) sb.AppendLine("    fatal(\"control flow fell off the end of a function\");");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private readonly record struct StepResult(bool FallsThrough, int? JumpTarget);

        private string Var(Flow st, int depth, int slot, ISet<string> locals)
        {
            int scopeIndex = st.Scopes.Count - 1 - depth;
            if (scopeIndex < 0) throw new NativeNotSupportedException("access to a variable outside of the function (closures are not supported yet)");
            int id = st.Scopes[scopeIndex].Id;
            if (id == GlobalScope) { _globals.Add(slot); return $"G{slot}"; }
            string v = id == FunctionScope ? $"P{slot}" : $"B{id}_{slot}";
            locals.Add(v);
            return v;
        }

        /// <summary>Applies the effect of one instruction to <paramref name="st"/>; with a builder it also emits the C++.</summary>
        private StepResult Step(Chunk chunk, Instr ins, Flow st, StringBuilder? sb, string fn, bool isMain, ISet<string> locals)
        {
            int d = st.Depth;
            string S(int k) => $"s{k}";
            void E(string text) { sb?.Append("    ").AppendLine(text); }
            void Need(int n)
            {
                if (d < n) throw new NativeNotSupportedException($"stack underflow at {ins.Addr} in {fn}");
            }
            StepResult Next() { st.Depth = d; return new StepResult(true, null); }

            switch (ins.Op)
            {
                case OpCode.LoadConst:
                    E($"{S(d)} = {Constant(chunk.Constants[ins.A[0]])};");
                    d++; return Next();
                case OpCode.Pop:
                    Need(1); d--; return Next();
                case OpCode.Dup:
                    Need(1); E($"{S(d)} = {S(d - 1)};"); d++; return Next();
                case OpCode.Swap:
                    Need(2); E($"{{ Value t = {S(d - 1)}; {S(d - 1)} = {S(d - 2)}; {S(d - 2)} = t; }}"); return Next();

                case OpCode.DeclareLocal:
                {
                    Need(1);
                    var (id, declared) = st.Scopes[^1];
                    if (id == GlobalScope) { _globals.Add(declared); E($"G{declared} = {S(d - 1)};"); }
                    else
                    {
                        string v = id == FunctionScope ? $"P{declared}" : $"B{id}_{declared}";
                        locals.Add(v);
                        E($"{v} = {S(d - 1)};");
                    }
                    st.Scopes[^1] = (id, declared + 1);
                    d--; return Next();
                }
                case OpCode.LoadLocal:
                    E($"{S(d)} = {Var(st, ins.A[0], ins.A[1], locals)};");
                    d++; return Next();
                case OpCode.StoreLocal:
                    Need(1); E($"{Var(st, ins.A[0], ins.A[1], locals)} = {S(d - 1)};"); return Next();
                case OpCode.StoreLocalPop:
                    Need(1); E($"{Var(st, ins.A[0], ins.A[1], locals)} = {S(d - 1)};"); d--; return Next();
                case OpCode.LoadGlobal:
                    _globals.Add(ins.A[0]); E($"{S(d)} = G{ins.A[0]};"); d++; return Next();
                case OpCode.StoreGlobal:
                    Need(1); _globals.Add(ins.A[0]); E($"G{ins.A[0]} = {S(d - 1)};"); return Next();
                case OpCode.StoreGlobalPop:
                    Need(1); _globals.Add(ins.A[0]); E($"G{ins.A[0]} = {S(d - 1)};"); d--; return Next();
                case OpCode.ArithLocalConstPop:
                {
                    string v = Var(st, ins.A[0], ins.A[1], locals);
                    E($"{v} = {(ins.A[3] == 0 ? "add" : "sub")}({v}, {Constant(chunk.Constants[ins.A[2]])});");
                    return Next();
                }
                case OpCode.ArithGlobalConstPop:
                {
                    _globals.Add(ins.A[0]);
                    E($"G{ins.A[0]} = {(ins.A[2] == 0 ? "add" : "sub")}(G{ins.A[0]}, {Constant(chunk.Constants[ins.A[1]])});");
                    return Next();
                }

                case OpCode.Add: return Binary("add");
                case OpCode.Sub: return Binary("sub");
                case OpCode.Mul: return Binary("mul");
                case OpCode.Div: return Binary("divide");
                case OpCode.Mod: return Binary("modulo");
                case OpCode.BitAnd: return Binary("bitAnd");
                case OpCode.BitOr: return Binary("bitOr");
                case OpCode.BitXor: return Binary("bitXor");
                case OpCode.ShiftLeft: return Binary("shl");
                case OpCode.ShiftRight: return Binary("shr");
                case OpCode.Neg: return Unary("negate");
                case OpCode.LogicalNot: return Unary("lnot");
                case OpCode.BitNot: return Unary("bitNot");

                case OpCode.Eq: return Compare("eq", false);
                case OpCode.NotEq: return Compare("eq", true);
                case OpCode.Lt: return Compare("lt", false);
                case OpCode.LtEq: return Compare("le", false);
                case OpCode.Gt: return Compare("gt", false);
                case OpCode.GtEq: return Compare("ge", false);

                case OpCode.Jump:
                    E($"goto L{ins.A[0]};");
                    return new StepResult(false, ins.A[0]);
                case OpCode.JumpIfFalse:
                    Need(1); E($"if (!truthy({S(d - 1)})) goto L{ins.A[0]};"); d--; st.Depth = d;
                    return new StepResult(true, ins.A[0]);
                case OpCode.JumpIfFalsePeek:
                    Need(1); E($"if (!truthy({S(d - 1)})) goto L{ins.A[0]};");
                    return new StepResult(true, ins.A[0]);
                case OpCode.JumpIfTruePeek:
                    Need(1); E($"if (truthy({S(d - 1)})) goto L{ins.A[0]};");
                    return new StepResult(true, ins.A[0]);
                case OpCode.JumpIfNotLt: return JumpIfNot("lt", false);
                case OpCode.JumpIfNotLtEq: return JumpIfNot("le", false);
                case OpCode.JumpIfNotGt: return JumpIfNot("gt", false);
                case OpCode.JumpIfNotGtEq: return JumpIfNot("ge", false);
                case OpCode.JumpIfNotEq: return JumpIfNot("eq", false);
                case OpCode.JumpIfNotNotEq: return JumpIfNot("eq", true);

                case OpCode.EnterScope:
                    st.Scopes.Add((ins.Addr, 0)); return Next();
                case OpCode.ExitScope:
                    if (st.Scopes.Count <= 1) throw new NativeNotSupportedException($"ExitScope without scope at {ins.Addr} in {fn}");
                    st.Scopes.RemoveAt(st.Scopes.Count - 1); return Next();

                case OpCode.CallNative:
                {
                    int argc = ins.A[1];
                    Need(argc);
                    string native = ins.A[0] < _natives.Count ? _natives[ins.A[0]] : "?";
                    if (native == "print" && argc == 1)
                    {
                        E($"{S(d - 1)} = print({S(d - 1)});");
                        return Next();
                    }
                    throw new NativeNotSupportedException($"native function '{native}' (called in {fn})");
                }
                case OpCode.CallStaticMethod:
                {
                    int argc = ins.A[2];
                    Need(argc);
                    string cls = chunk.Constants[ins.A[0]].AsString(), method = chunk.Constants[ins.A[1]].AsString();
                    if (!_program.Program.Classes.TryGetValue(cls, out var rc))
                        throw new NativeNotSupportedException($"unknown class '{cls}'");
                    var proto = rc.FindMethodWithAccess(method, argc).Proto
                        ?? throw new NativeNotSupportedException($"{cls}.{method} with {argc} argument(s) not found");
                    if (!proto.IsStatic) throw new NativeNotSupportedException($"{cls}.{method} is not static");
                    if (proto.ParamCount != argc) throw new NativeNotSupportedException($"{cls}.{method}: default arguments");
                    int f = FunctionIndex(proto);
                    string args = string.Join(", ", Enumerable.Range(d - argc, argc).Select(S));
                    E($"{S(d - argc)} = f{f}({args});");
                    d = d - argc + 1; return Next();
                }
                case OpCode.Return:
                    Need(1); E($"return {S(d - 1)};");
                    if (isMain) throw new NativeNotSupportedException("return in top-level code");
                    return new StepResult(false, null);
                case OpCode.Halt:
                    if (!isMain) throw new NativeNotSupportedException("Halt in a function");
                    E("return;");
                    return new StepResult(false, null);
                case OpCode.SetTimeout:
                case OpCode.SetAutoSync:
                    // Waiting functions and queue processing do not exist in the native backend yet; the directives are no-ops there.
                    if (ins.Op == OpCode.SetTimeout) { Need(1); d--; }
                    return Next();

                default:
                    throw new NativeNotSupportedException($"opcode {ins.Op} (in {fn} at {ins.Addr})");
            }

            StepResult Binary(string fnName)
            {
                Need(2); E($"{S(d - 2)} = {fnName}({S(d - 2)}, {S(d - 1)});"); d--; return Next();
            }
            StepResult Unary(string fnName)
            {
                Need(1); E($"{S(d - 1)} = {fnName}({S(d - 1)});"); return Next();
            }
            StepResult Compare(string fnName, bool negate)
            {
                Need(2); E($"{S(d - 2)} = Bool({(negate ? "!" : "")}{fnName}({S(d - 2)}, {S(d - 1)}));"); d--; return Next();
            }
            StepResult JumpIfNot(string fnName, bool negate)
            {
                Need(2); E($"if (!({(negate ? "!" : "")}{fnName}({S(d - 2)}, {S(d - 1)}))) goto L{ins.A[0]};");
                d -= 2; st.Depth = d;
                return new StepResult(true, ins.A[0]);
            }
        }

        private int FunctionIndex(FunctionProto proto)
        {
            if (_functionIndex.TryGetValue(proto, out int index)) return index;
            index = _functions.Count;
            _functions.Add(proto);
            _functionIndex[proto] = index;
            _pending.Enqueue(proto);
            return index;
        }

        // -------------------------------------------------------------------------------------------------------------
        // Constants
        // -------------------------------------------------------------------------------------------------------------
        private int UnitId(Unit? unit)
        {
            if (unit == null || unit.IsUnitless) return 0;
            for (int i = 1; i < _units.Count; i++) if (_units[i].Equals(unit)) return i;
            _units.Add(unit);
            return _units.Count - 1;
        }

        private string Constant(Value v)
        {
            switch (v.Kind)
            {
                case ValueKind.Int:
                {
                    long i = v.AsInt();
                    string lit = i == long.MinValue ? "INT64_MIN" : i.ToString(CultureInfo.InvariantCulture) + "LL";
                    int unit = UnitId(v.Unit);
                    return unit == 0 ? $"Int({lit})" : $"Int({lit}, {unit})";
                }
                case ValueKind.Float:
                {
                    int unit = UnitId(v.Unit);
                    string lit = DoubleLiteral(v.AsFloat(), _program.FloatWidth == 32);
                    return unit == 0 ? $"Float({lit})" : $"Float({lit}, {unit})";
                }
                case ValueKind.Bool: return v.AsBool() ? "Bool(true)" : "Bool(false)";
                case ValueKind.Char: return $"Char({(int)v.AsChar()})";
                case ValueKind.Undefined: { int unit = UnitId(v.Unit); return unit == 0 ? "Undef()" : $"Undef({unit})"; }
                case ValueKind.String:
                {
                    string s = v.AsString();
                    if (!_stringIndex.TryGetValue(s, out int index)) { index = _strings.Count; _strings.Add(s); _stringIndex[s] = index; }
                    return $"Str(&K{index})";
                }
                default:
                    throw new NativeNotSupportedException($"constant of kind {v.Kind}");
            }
        }

        private static string DoubleLiteral(double d, bool single)
        {
            if (double.IsNaN(d)) return single ? "std::nanf(\"\")" : "std::nan(\"\")";
            if (double.IsPositiveInfinity(d)) return single ? "HUGE_VALF" : "HUGE_VAL";
            if (double.IsNegativeInfinity(d)) return single ? "-HUGE_VALF" : "-HUGE_VAL";
            if (d == 0 && double.IsNegative(d)) return single ? "-0.0f" : "-0.0";
            string text = single ? ((float)d).ToString("R", CultureInfo.InvariantCulture) : d.ToString("R", CultureInfo.InvariantCulture);
            if (!(text.Contains('.') || text.Contains('E') || text.Contains('e'))) text += ".0";
            return single ? text + "f" : text;
        }

        private static string CString(string s) => CString(Encoding.UTF8.GetBytes(s));

        /// <summary>A C string literal of the bytes (octal escapes for everything outside printable ASCII).</summary>
        private static string CString(byte[] bytes)
        {
            var sb = new StringBuilder("\"");
            foreach (byte b in bytes)
            {
                if (b == '"' || b == '\\') sb.Append('\\').Append((char)b);
                else if (b >= 0x20 && b < 0x7F && b != '?') sb.Append((char)b); // '?' avoids trigraphs
                else sb.Append('\\').Append(Convert.ToString(b, 8).PadLeft(3, '0'));
            }
            return sb.Append('"').ToString();
        }
    }
}
